#!/bin/env bash
#
# Requirements: curl & xmllint
#

SERVER_IP=""
SERVER_PORT="32400"
PLEX_TOKEN=""

case $1 in
  tv|TV)
    SECTION="2"
    TYPE="newest"
  ;;
  movies|MOVIES)
    SECTION="1"
    TYPE="recentlyAdded"
  ;;
  *)
    echo "Options: tv, movies"
    exit 1
  ;;
esac

curl -s --insecure "https://${SERVER_IP}:${SERVER_PORT}/library/sections/${SECTION}/${TYPE}?X-Plex-Token=${PLEX_TOKEN}" > db.xml
xmllint db.xml --xpath "/MediaContainer/Video[position()>=10]/@*[name()='title' or name()='grandparentTitle' or name()='parentTitle']"
exit 0