# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=1
      - >-
        {{- if eq .Os "linux" }}
          {{- if eq .Arch "amd64"}}CC=x86_64-linux-musl-gcc{{- end }}
          {{- if eq .Arch "arm64"}}CC=aarch64-linux-musl-gcc{{- end }}
        {{- end }}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/ssalvatori/zbot-telegram/zbot.version={{ .Version }}
      - -X github.com/ssalvatori/zbot-telegram/zbot.gitHash={{ .ShortCommit }}
      - -X github.com/ssalvatori/zbot-telegram/zbot.buildTime={{ .Date }}
    ignore:
      - goos: darwin
        goarch: amd64
      - goos: darwin
        goarch: 386

archives:
  - format_overrides:
    - formats: ["tar.gz"]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
