language: go
go:
  - 1.15.x
env:
  - BOT_TOKEN=1234:334
before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/mitchellh/gox
  - go get github.com/modocache/gover
script:
  - go test -v github.com/ssalvatori/zbot-telegram/zbot -coverprofile=zbot.coverprofile
  - go test -v github.com/ssalvatori/zbot-telegram/utils -coverprofile=utils.coverprofile
  - go test -v github.com/ssalvatori/zbot-telegram/user -coverprofile=user.coverprofile
  - go test -v github.com/ssalvatori/zbot-telegram/db -coverprofile=db.coverprofile
  - go test -v github.com/ssalvatori/zbot-telegram/commands -coverprofile=db.coverprofile
  - $HOME/gopath/bin/gover
  - $HOME/gopath/bin/goveralls -coverprofile gover.coverprofile -service travis-ci --ignore=db/mock.go,db/db.go,db/sqlite.go
after_success:
  - $HOME/gopath/bin/gox -osarch="linux/amd64 linux/386" -cgo -ldflags "-X github.com/ssalvatori/zbot-telegram/zbot.version=`git describe --tags` -X github.com/ssalvatori/zbot-telegram/zbot.buildTime=`TZ=UTC date -u '+%Y-%m-%dT%H:%M:%SZ'` -X github.com/ssalvatori/zbot-telegram/zbot.gitHash=`git rev-parse --short HEAD`" -output "dist/{{.Dir}}-{{.OS}}-{{.Arch}}"
deploy:
  provider: releases
  cleanup: false
  file_glob: true
  file: dist/*
  api_key: "$GITHUB_API_SECURED"
  on:
    tags: true
