BEGIN TRANSACTION;
CREATE TABLE `users` (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	`username`	TEXT NOT NULL,
	`level`	INTEGER DEFAULT 10
);
CREATE TABLE "ignore_list" (
    `id` INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
    `username` TEXT NOT NULL,
    `since` INTEGER NOT NULL,
    `until` INTEGER NOT NULL
);
CREATE TABLE "definitions" (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`term`	TEXT UNIQUE,
	`meaning`	TEXT NOT NULL,
	`author`	TEXT NOT NULL,
	`locked`	INTEGER DEFAULT 0,
	`active`	INTEGER DEFAULT 1,
	`date`	TEXT DEFAULT '0000-00-00',
	`hits`	INTEGER DEFAULT 0,
	`link`	INTEGER,
	`locked_by`	TEXT
);
COMMIT;
