FROM alpine:3.12

RUN apk add --update \
    wget \
    sqlite \
    jq \
    && rm -rf /var/cache/apk/*

RUN apk --no-cache add ca-certificates \
    && wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub \
    && wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.31-r0/glibc-2.31-r0.apk \
    && apk add glibc-2.31-r0.apk \
    && rm -rf /var/cache/apk/*

WORKDIR /app

COPY zbot-telegram-linux-amd64 /app/zbot-telegram-linux-amd64
RUN chmod +x /app/zbot-telegram-linux-amd64
CMD ["/app/zbot-telegram-linux-amd64"]
